version: '3.4'

services:
  walletapi:
    image: walletapi
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 4001:4001
